### ISSUE TITLE
2.7.1 still has rotation offset bug

### ISSUE THREAD

**Issue by ParticleCore** [alexvasilkov/GestureViews#168] opened 2021-04-16 17:52 UTC
I have noticed that the release version does not match the current branch version in your master. As a result, the 2.7.1 still has a bug with rotation that causes it to rotate about an incorrect center point, but this is already corrected in the master branch in the `GestureController` file.

The commit with the fix was pushed 2 days after 2.7.1 was released so it missed that one:

https://github.com/alexvasilkov/GestureViews/commit/f2ed7a6beb9b9e517016d4203afdac9daf96b123#diff-9b17b755bea484fcfcaba9988fd0cbacc41e74723bdfcef36bbaab86ce0d218e

**Comment by alexvasilkov** [comment] 2021-04-19 10:56
But why do you think it should be part of 2.7.1? Full list of included changes can be found here: https://github.com/alexvasilkov/GestureViews/releases/tag/v2.7.1

Can you describe your issue? Are you sure it is fixed in the latest code from the repository?

**Comment by ParticleCore** [comment] 2021-04-19 17:03
Rotation bug in 2.1.7

![1](https://user-images.githubusercontent.com/9222661/115275251-90bfc380-a10f-11eb-8334-68505db80e0d.gif)


Rotation bug fixed in latest repository version

![2](https://user-images.githubusercontent.com/9222661/115275306-9f0ddf80-a10f-11eb-89a7-5da7dca03644.gif)


I only reverted the commit above for the file `GestureController` and it was sufficient to cause the problem that exists in 2.1.7

**Comment by alexvasilkov** [comment] 2021-04-19 17:08
Yeah, I see, do you need the fix to be released asap?

**Comment by ParticleCore** [comment] 2021-04-19 17:38
No need to hurry, fortunately this does not affect its usability, it is merely a UI inconvenience at this point for me.

**Comment by ParticleCore** [comment] 2021-05-20 16:55
@alexvasilkov out of curiosity, is there any rough estimate on when the version with a fix for this is going to be released?

**Comment by alexvasilkov** [comment] 2021-05-26 10:48
Version 2.8.0 is released now.

But I checked out source code and sample app for v2.7.0 and v2.7.1 and can't reproduce the issue from the gifs above. Are you sure you didn't do any extra modifications that could cause this issue? There were no major changes to `GestureController` in v2.7.1 or earlier (at least in the past few years), so this issue must have been there for quite a while then.

**Closed by alexvasilkov** 2021-05-26 10:48 UTC
