### ISSUE TITLE
getController().enableScrollInViewPager  support ViewPager2

### ISSUE THREAD

**Issue by FireboltX** [alexvasilkov/GestureViews#182] opened 2023-03-29 03:58 UTC
Dear alexvasilkov:
Do you have any plans to enable "getController().enableScrollInViewPager" to support ViewPager2?
I've tried copy another GestureControllerForPager , and replace ViewPager to ViewPager2 ,but i had failed.
When i executed "getController().enableScrollInViewPager" in viewpager's adapter ,the image cannot slide any more.

**Comment by alexvasilkov** [comment] 2023-03-29 09:37
The old way to enable seamless scrolling with ViewPager was more like a hack. A better approach would be to use [`NestedScrollingChild`](https://developer.android.com/reference/androidx/core/view/NestedScrollingChild) / [`NestedScrollingParent`](https://developer.android.com/reference/androidx/core/view/NestedScrollingParent) mechanizm, but it's a rather complicated stuff that I didn't have time to implement yet.

Meanwhile I'll close this issue as a duplicate of #176, you can add your comments there.

**Closed by alexvasilkov** 2023-03-29 09:37 UTC
