### ISSUE TITLE
OnClickListener not working 

### ISSUE THREAD

**Issue by supercoder123** [alexvasilkov/GestureViews#75] opened 2017-07-03 13:08 UTC
i have a full screen imageview placed inside a relative layout...i tried using gesture image view but the on click listener was not working .So i replaced it with a normal Image View and then the on click listener works. But it's useless as i need zoom and pan capabilites

**Comment by alexvasilkov** [comment] 2017-07-03 13:11
Duplicate of #74

**Closed by alexvasilkov** 2017-07-03 13:11 UTC
Labels: duplicate
