### ISSUE TITLE
How about ViewPager2 integration?

### ISSUE THREAD

**Issue by zhombie** [alexvasilkov/GestureViews#170] opened 2021-05-12 20:53 UTC
Android Jetpack released [ViewPager2](https://developer.android.com/jetpack/androidx/releases/viewpager2), which handles  on its own recycling process and maybe the ViewPager will be deprecated soon

**Comment by alexvasilkov** [comment] 2021-05-26 10:16
Duplicate of #144

**Closed by alexvasilkov** 2021-05-26 10:16 UTC
