### ISSUE TITLE
setOnclickListener disables Gestures

### ISSUE THREAD

**Issue by VasilisKatsoris** [alexvasilkov/GestureViews#82] opened 2017-08-17 22:33 UTC
Using a GestureFrameLayout if I set an onClickListener to the layout or any child of it, the Gestures no longer work. Am I using something wrong or is this a limitation/bug ?

**Comment by alexvasilkov** [comment] 2017-08-22 12:00
Seems like a duplicate of issue #74

**Closed** 2017-08-30 05:19 UTC
Labels: duplicate
