### ISSUE TITLE
The child view of GestureFrameLayout, which draws a large number of figures, will result in a jam

### ISSUE THREAD

**Issue by ZhuSky** [alexvasilkov/GestureViews#158] opened 2020-05-25 11:41 UTC
When the sub view of gestureframelayout draws a large number of round (similar to chessboard) views, the scaling is very difficult.

**Comment by alexvasilkov** [comment] 2020-05-29 07:03
As I understand the problem is not really in `GestureFrameLayout`, drawing large number of views is very inefficient in Android, and it will be slow even if you'll place them into regular `ScrollView`.

If you ned to draw a large amount of stuff then consider doing it with a custom view directly into canvas.

I'll close this ticket, but please reopen it if you can provide evidences that the issue actually comes from `GestureFrameLayout` usage.

**Closed by alexvasilkov** 2020-05-29 07:03 UTC

**Comment by ZhuSky** [comment] 2020-05-29 07:05
@alexvasilkov I see thank you
